# Advanced Array Operations (NumPy)
**These operations help you:**
- Manipulate arrays efficiently
- Understand memory behavior
- Optimize performance
- Write ML-ready NumPy code

## 1. np.tile()
- np.tile() repeats an array in blocks to form a larger array.

- Syntax
  - np.tile(array, reps)

In [1]:
# Example (1D)
import numpy as np

arr = np.array([1, 2, 3])

print(np.tile(arr, 3))

[1 2 3 1 2 3 1 2 3]


In [2]:
# Example (2D)
arr = np.array([[1, 2],
                [3, 4]])

print(np.tile(arr, (2, 3)))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


### ML Use Case
- Creating repeated patterns
- Data augmentation
- Broadcasting alternatives (but uses more memory)

## 2. np.repeat()
 - Repeats each element of an array.

- Syntax
  - np.repeat(array, repeats, axis=None)

In [3]:
# Example (1D)
arr = np.array([1, 2, 3])

print(np.repeat(arr, 2))

[1 1 2 2 3 3]


In [4]:
# Example (2D with Axis)
arr = np.array([[1, 2],
                [3, 4]])

print(np.repeat(arr, 2, axis=0))

[[1 2]
 [1 2]
 [3 4]
 [3 4]]


- Difference: tile() vs repeat()
| Feature | tile        | repeat              |
| ------- | ----------- | ------------------- |
| Repeats | Whole array | Individual elements |
| Memory  | Higher      | Lower               |
| Pattern | Block-based | Element-based       |

## 3. np.unique()
- Returns unique elements from an array.

- Syntax
  - np.unique(array, return_counts=False)

In [5]:
arr = np.array([1, 2, 2, 3, 3, 3])
print(np.unique(arr))

[1 2 3]


In [6]:
# With Counts
values, counts = np.unique(arr, return_counts=True)
print(values)
print(counts)

[1 2 3]
[1 2 3]


### ML Use Case
- Label encoding
- Class frequency
- Removing duplicates

# 4. np.bincount()
- Counts frequency of non-negative integers.

- Syntax
  - np.bincount(array)

In [7]:
arr = np.array([0, 1, 1, 2, 2, 2])
print(np.bincount(arr))

[1 2 3]


**Output Explanation**
- Index → number
- Value → count

## Difference: unique() vs bincount()
| Feature    | unique     | bincount               |
| ---------- | ---------- | ---------------------- |
| Works with | Any values | Non-negative ints only |
| Speed      | Slower     | Faster                 |
| ML use     | Labels     | Class counts           |

# 5. Reshape Order ('C' vs 'F')
## What Is Reshape Order?
- Controls how elements are read and written during reshape.

### 'C' Order (Row-major – Default)

In [10]:
arr = np.arange(6)
print(arr.reshape((2,3), order='C'))
# Fills rows first

[[0 1 2]
 [3 4 5]]


### 'F' Order (Column-major)

In [11]:
print(arr.reshape((2,3), order='F'))
# Fills columns first

[[0 2 4]
 [1 3 5]]


**Why This Matters**
- Memory layout
- Performance
- Compatibility with MATLAB / Fortran

# 6. ndarray.flags
- Shows internal memory information about an array.

In [12]:
arr = np.array([[1, 2],
                [3, 4]])
print(arr.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Important Flags
| Flag         | Meaning        |
| ------------ | -------------- |
| C_CONTIGUOUS | Row-major      |
| F_CONTIGUOUS | Column-major   |
| OWNDATA      | Owns memory    |
| WRITEABLE    | Can modify     |
| ALIGNED      | Memory aligned |