# What is dtype in NumPy?
- In NumPy, dtype (data type) defines what kind of data is stored in a NumPy array.

- It specifies:

  - Type of data (int, float, bool, etc.)

  - Size of each element in memory

  - How NumPy interprets the binary data

# Why dtype is Important

 - Controls memory usage

 - Determines precision of data

 - Affects speed of computation

 - Ensures data consistency

# Difference Between Python List and NumPy dtype
- Python List
   - Stores different data types

   - Each element is a separate Python object

   - More memory usage

In [1]:
data = [1, 2.5, "hello"]

- NumPy Array
  - Stores same data type

  - Fixed memory block

  - Faster operations

In [1]:
import numpy as np
arr = np.array([1, 2, 3])

# Checking dtype of an Array
  - Using dtype attribute

In [3]:
arr = np.array([10, 20, 30])
print(arr.dtype)

int64


# Data Types
- The bit is the most basic unit of information in computing
- The byte is a unit of information which contains 8 bits.
- Bit = 1
- Byte = 10110001

|         Bits | Integer | Unsigned Integer | Float       | Complex       | Boolean |
| -----------: | ------- | ---------------- | ----------- | ------------- | ------- |
|   **8 bits** | `int8`  | `uint8`          | —           | —             | `bool`  |
|  **16 bits** | `int16` | `uint16`         | `float16`   | —             | —       |
|  **32 bits** | `int32` | `uint32`         | `float32`   | `complex64`   | —       |
|  **64 bits** | `int64` | `uint64`         | `float64`   | `complex128`  | —       |
| **128 bits** | —       | —                | `float128`* | `complex256`* | —       |


# Data Type
- **Byte string** are constrained by the character encoding used in character encoding like ASCII, each char is represented by byte, limiting the available character too the 128 ASCII character.
- **Unicode string** cover a much larger range of character, including those from various language and special symbols.
- **"Object"** data type is used for all other data types.

# Three of Data Types
- **Byte string**
    - bytes
    - bytes_
    - S
    - a

- **Unicode Strings**
    - U
    - str
    - str_
    - unicode

- **Object**
    - object
    - O

# Common NumPy Data Types (dtypes)
1. Integer Types
| dtype | Description    |
| ----- | -------------- |
| int8  | 8-bit integer  |
| int16 | 16-bit integer |
| int32 | 32-bit integer |
| int64 | 64-bit integer |

In [4]:
np.array([1,2,3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

2. Floating-Point Types
| dtype   | Description                |
| ------- | -------------------------- |
| float16 | Half precision             |
| float32 | Single precision           |
| float64 | Double precision (default) |

In [5]:
np.array([1.5, 2.3], dtype=np.float32)

array([1.5, 2.3], dtype=float32)

3. Boolean Type
- Stores True or False.

In [12]:
arr_b = np.array([True, False, True])

In [13]:
print(arr_b.dtype)

bool


4. Complex Numbers

In [14]:
arr_c = np.array([1+2j, 3+4j])
print(arr_c.dtype)

complex128


5. String Type

In [15]:
arr_s = np.array(["apple", "banana", "cherry"])
print(arr_s.dtype)

<U6


6. Object Type

- Used when data types are mixed.


In [16]:
arr_o = np.array([1, "hello", 2.5], dtype=object)
print(arr_o.dtype)

object


# Automatic dtype Conversion (Type Promotion)

In [17]:
arr_a = np.array([1, 2.5, 3])
print(arr_a)
print(arr_a.dtype)

[1.  2.5 3. ]
float64


- NumPy converts int → float
- Because float can store integer values

- Specifying dtype Manually

In [18]:
arr = np.array([1,2,3], dtype=float)

- Memory Comparison

In [19]:
a = np.array([1,2,3], dtype=np.int8)
b = np.array([1,2,3], dtype=np.int64)

print(a.itemsize)
print(b.itemsize)

1
8


# Changing dtype (astype())
- Used to convert array to another dtype.

In [20]:
arr_d = np.array([1,2,3])
new_arr = arr_d.astype(float)

print(new_arr)
print(new_arr.dtype)

[1. 2. 3.]
float64


- Important Note

   - astype() creates a new copy

   - Original array remains unchanged

# itemsize and nbytes

- itemsize

   - Size of one element in bytes.

In [21]:
arr = np.array([1,2,3], dtype=np.int32)
print(arr.itemsize)

4


- nbytes

  - Total memory used.

In [22]:
print(arr.nbytes)

12


In [23]:
arr1 = np.array([1.123456789], dtype=np.float32)
arr2 = np.array([1.123456789], dtype=np.float64)

print(arr1)
print(arr2)

[1.1234568]
[1.12345679]


In [2]:
x = np.array([1, 344, 6, - 45, -35], dtype = "complex128")
x, x.dtype

(array([  1.+0.j, 344.+0.j,   6.+0.j, -45.+0.j, -35.+0.j]),
 dtype('complex128'))

In [3]:
y = np.array([2,4,6,3,6], dtype="f2")
y, y.dtype

(array([2., 4., 6., 3., 6.], dtype=float16), dtype('float16'))

In [5]:
z = np.array([0,1,True,False,20,11], dtype="bool")
z, z.dtype

(array([False,  True,  True, False,  True,  True]), dtype('bool'))