# What is Broadcasting?

- Broadcasting is a NumPy mechanism that allows arrays of different shapes to be used together in arithmetic and vectorized operations without explicitly copying data.

- NumPy automatically stretches the smaller array to match the larger array during operations.

## Why Broadcasting is Important

- Broadcasting:

   - Eliminates loops (faster code)

   - Saves memory

   - Makes code cleaner and readable

   - Is heavily used in Machine Learning algorithms

Almost every ML formula relies on broadcasting.

### Rules of Broadcasting 

- NumPy follows strict rules when broadcasting arrays.

- **Rule 1: Compare Shapes from Right to Left**

   - When two arrays are operated together:

      - NumPy compares their shapes starting from the last dimension

- **Rule 2: Dimensions Are Compatible If**

   - Two dimensions are compatible when:

      - They are equal, OR

      - One of them is 1

- **Rule 3: Missing Dimensions Are Treated as 1**

   - If one array has fewer dimensions:

      - NumPy assumes missing dimensions are size 1

- **Rule 4: If Rules Fail → Error**

   - If dimensions are not equal and neither is 1 →
      -  ValueError: operands could not be broadcast together

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])
result = arr + 10

print(result)

[11 12 13 14]


### Why Scalar Broadcasting Matters in ML

- Used in:

   - Bias addition in neural networks

   - Normalization

   - Feature scaling

### Different Shape Operations

In [2]:
#Example 2: Same Shape Arrays (No Broadcasting)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print(A + B)


# Shapes (3,) and (3,) → directly compatible

[5 7 9]


In [3]:
# Example 3: 1D with 2D Array
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])

print(A + B)

[[11 22 33]
 [14 25 36]]


### Row Broadcasting
- When a 1D array matches the number of columns, it is broadcast row-wise.

In [4]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

row = np.array([10, 20, 30])

print(matrix + row)

# Each row gets [10, 20, 30]

[[11 22 33]
 [14 25 36]]


- **ML Use Case**

    - Adding bias vector to each data sample

    - Feature-wise transformations

### Column Broadcasting
When a column vector is broadcast across columns.

In [5]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

col = np.array([[10],
                [20]])

print(matrix + col)

[[11 12 13]
 [24 25 26]]


### Broadcasting with Higher Dimensions


- **Broadcasting Process**

  - Compare from right

  - (4) matches (4)

  - Missing dims treated as 1

In [6]:
# Example 4: 3D Broadcasting
A = np.ones((2, 3, 4))
B = np.ones((4,))

print((A + B).shape)

# Result shape:

# (2, 3, 4)

(2, 3, 4)


### Broadcasting Failure Example

In [7]:
A = np.ones((3, 2))
B = np.ones((3,))

A + B

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

- Error because:

  - (3, 2)
  - (3,)


- Last dimensions:

   - 2 ≠ 3 and neither is 1