# Why Copy & View Concept Exists

- NumPy is designed to:

   - Handle large data

   - Use minimum memory

   - Be fast

- To achieve this, NumPy sometimes does NOT create new data, it just creates a new way to see the same data.

- That’s where View (Shallow Copy) and Copy (Deep Copy) come in.

# 1. View (Shallow Copy)
- A View is a new array object that:

   - Refers to the same memory

   - Shares data with original array

   - Does NOT create new data

- Change in one affects the other

- How View is Created
  - Common operations that return a View:

     - Slicing

     - reshape()

     - ravel()

     - transpose()

     - view()

In [1]:
# Example 1: View using slicing
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = a[1:4]      # slicing creates view

b[0] = 999

print(a)
print(b)

[ 10 999  30  40  50]
[999  30  40]


- Changing b changed a → View confirmed

In [2]:
# Example 2: View using reshape
a = np.array([1,2,3,4])
b = a.reshape(2,2)

b[0,0] = 100

print(a)
print(b)

[100   2   3   4]
[[100   2]
 [  3   4]]


In [3]:
# Explicit View using view()
a = np.array([1,2,3])
b = a.view()

b[1] = 500
print(a)

[  1 500   3]


- Key Properties of View
| Property    | Value |
| ----------- | ----- |
| New memory  | ❌ No  |
| Shares data | ✔ Yes |
| Fast        | ✔ Yes |
| Risky       | ✔ Yes |

# 2. Copy (Deep Copy)
- A Copy creates:

   - A completely new array

   - Separate memory

   - Independent data

- Change in one does NOT affect the other

- How Copy is Created
   - Methods:

      - copy()

      - flatten()

      - astype()

In [4]:
# Example 1: Using copy()
a = np.array([10, 20, 30])
b = a.copy()

b[0] = 999

print(a)
print(b)

[10 20 30]
[999  20  30]


In [5]:
# Example 2: flatten() creates copy
a = np.array([[1,2],[3,4]])
b = a.flatten()

b[0] = 100
print(a)

[[1 2]
 [3 4]]


- Key Properties of Copy
| Property    | Value |
| ----------- | ----- |
| New memory  | ✔ Yes |
| Shares data | ❌ No  |
| Safe        | ✔ Yes |
| Slower      | ✔ Yes |

# 3. Memory Sharing Concepts

# How to Check Memory Sharing
1. base attribute

In [6]:
print(b.base)

None


- If base is None → Copy

- If base is not None → View

2. np.shares_memory()

In [7]:
np.shares_memory(a, b)

False

In [8]:
a = np.array([1,2,3])
b = a[1:]

print(np.shares_memory(a, b))

True


- Why Memory Sharing is Dangerous