# Indexing & Slicing in NumPy

1. What is Indexing?
- Indexing is the process of accessing a single element from a NumPy array using its position (index).

- NumPy indexing starts from 0 (zero-based indexing), just like Python.

2. What is Slicing?

- Slicing means extracting a portion (sub-array) from a NumPy array.

- Instead of accessing one value, slicing returns multiple values.

- 1D Array Indexing

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

In [2]:
# Positive Indexing
print(arr[0])   # first element
print(arr[2])   # third element

10
30


- Why Indexing is Important

  - Access specific data

  - Modify values

  - Perform calculations

- Negative Indexing (1D)

  - Negative indexing starts from the end of the array.

    - -1 → last element

    - -2 → second last

In [3]:
print(arr[-1])
print(arr[-3])

50
30


3. Basic Slicing in 1D Arrays
- Syntax
    - array[start : stop : step]

       - start → starting index (inclusive)

       - stop → ending index (exclusive)

       - step → jump size

In [4]:
print(arr[1:4])

[20 30 40]


In [5]:
print(arr[::2]) #Step Example

[10 30 50]


# 4. 2D Array Indexing

In [6]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

In [7]:
# Access Single Element
print(arr2[0, 1])

2


In [8]:
# Row Access
print(arr2[1])

[4 5 6]


In [9]:
# Column Access
print(arr2[:, 2])

[3 6 9]


# 5. 2D Array Slicing
- Syntax
  - array[row_start:row_end , col_start:col_end]

In [10]:
print(arr2[0:2, 1:3])

[[2 3]
 [5 6]]


# 6. 3D Array Indexing

In [11]:
# 3D Array
arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

In [12]:
# Access Element
print(arr3[1, 0, 1])

6


In [13]:
# 3D Slicing Example
print(arr3[:, :, 0])

[[1 3]
 [5 7]]


# 7. Advanced Slicing
- Advanced slicing allows:

   - Complex selections

   - Skipping patterns

   - Sub-arrays without loops

In [14]:
print(arr2[::2, ::2])

[[1 3]
 [7 9]]


# 8. Fancy Indexing
Fancy indexing uses lists or arrays of indices to select elements.

In [15]:
# 1D Fancy Indexing
arr = np.array([10, 20, 30, 40, 50])

print(arr[[0, 2, 4]])

[10 30 50]


In [16]:
# 2D Fancy Indexing
print(arr2[[0,2], [1,2]])

[2 9]


- Fancy indexing returns a copy, not a view.

# 9. Boolean Indexing
- Boolean indexing selects elements based on conditions (True/False).

In [17]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[arr > 25])

[30 40 50]


In [18]:
# Multiple Conditions
print(arr[(arr > 20) & (arr < 50)])

[30 40]


- Replacing Values Using Boolean Index

In [19]:
arr[arr < 30] = 0
print(arr)

[ 0  0 30 40 50]
