# What is Joining and Splitting?
- Joining
   - Joining means combining two or more NumPy arrays into a single array along a specified axis.



- Splitting
   - Splitting means dividing one NumPy array into multiple smaller arrays.

# PART 1️ : JOINING ARRAYS

1. concatenate()
   - concatenate() joins multiple arrays along a specified axis.

- Syntax
   - np.concatenate((array1, array2, ...), axis=0)
 
 
- Rules

   - Arrays must have the same shape, except in the dimension corresponding to the joining axis.

   - Default axis is 0 (row-wise).

In [3]:
# Example: 1D Arrays
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))
print(result)

[1 2 3 4 5 6]


In [2]:
# Example: 2D Arrays (axis = 0)
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(np.concatenate((a, b), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
# Example: 2D Arrays (axis = 1)
print(np.concatenate((a, b), axis=1))

[[1 2 5 6]
 [3 4 7 8]]


2. hstack() (Horizontal Stack)
  - hstack() stacks arrays horizontally (column-wise).

  - Internally, it works like:

  - axis = 1

In [4]:
print(np.hstack((a, b)))

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
# 1D Array Case
x = np.array([1, 2])
y = np.array([3, 4])

print(np.hstack((x, y)))

[1 2 3 4]


3. vstack() (Vertical Stack)
  - vstack() stacks arrays vertically (row-wise).

  - Internally, it works like:

  - axis = 0

In [6]:
print(np.vstack((a, b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
# 1D Arrays Become 2D
print(np.vstack((x, y)))

[[1 2]
 [3 4]]


4. dstack() (Depth Stack)
  - dstack() stacks arrays along the third dimension (depth).

In [8]:
print(np.dstack((a, b)))

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


5. column_stack()
  - column_stack() stacks 1D arrays as columns into a 2D array.

In [9]:
c = np.array([1, 2, 3])
d = np.array([4, 5, 6])

print(np.column_stack((c, d)))

[[1 4]
 [2 5]
 [3 6]]


6. row_stack()
   - row_stack() stacks arrays row-wise.

- It is functionally equivalent to vstack().

In [10]:
print(np.row_stack((c, d)))

[[1 2 3]
 [4 5 6]]


C:\Users\HP\AppData\Local\Temp\ipykernel_31604\2969569534.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((c, d)))


- JOINING SUMMARY TABLE
| Function       | Joining Direction    |
| -------------- | -------------------- |
| concatenate()  | Axis-based           |
| hstack()       | Horizontal (columns) |
| vstack()       | Vertical (rows)      |
| dstack()       | Depth (3rd axis)     |
| column_stack() | Columns (1D → 2D)    |
| row_stack()    | Rows                 |

# PART 2️ : SPLITTING ARRAYS

1. split()
- split() divides an array into equal-sized sub-arrays.

- Syntax
   - np.split(array, sections, axis=0)

In [13]:
a = np.array([10, 20, 30, 40, 50, 60])

result = np.split(a, 3)
print(result)

[array([10, 20]), array([30, 40]), array([50, 60])]


- Important Rule
  - The array must be divisible equally, otherwise it raises an error.

2. hsplit()
  - hsplit() splits an array horizontally (column-wise).

In [4]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

print(np.hsplit(a, 2))

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [6]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.hsplit(a, 2)

In [7]:
for i in c:
    print(i)

[[1 2]
 [5 6]]
[[3 4]
 [7 8]]


3. vsplit()
  - vsplit() splits an array vertically (row-wise).

In [9]:
print(np.vsplit(a, 2))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


4. array_split()
  - array_split() splits an array into unequal parts if needed.

- It does not raise an error when equal division is not possible.

In [16]:
a = np.array([1, 2, 3, 4, 5])

print(np.array_split(a, 3))

[array([1, 2]), array([3, 4]), array([5])]


- SPLITTING SUMMARY TABLE
| Function      | Equal Division Required |
| ------------- | ----------------------- |
| split()       | Yes                     |
| hsplit()      | Yes                     |
| vsplit()      | Yes                     |
| array_split() | No                      |

In [3]:
import numpy as np
x = np.array([[4,5,6],
              [1,2,3]])
y = np.array([[10,11,12],
              [7,8,9]])
print(f"x: \n {x} \ny: {y} \n")
print("Array Result : \n", np.concatenate((x,y), axis = 0)) # Row - wise

x: 
 [[4 5 6]
 [1 2 3]] 
y: [[10 11 12]
 [ 7  8  9]] 

Array Result : 
 [[ 4  5  6]
 [ 1  2  3]
 [10 11 12]
 [ 7  8  9]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))
print(result)

[1 2 3 4 5 6]
