# NumPy provides a powerful sub-module called:

 - np.linalg


It contains optimized functions for matrix operations, systems of equations, and vector mathematics.

### Why Linear Algebra Is Important

Linear Algebra is the mathematical backbone of:

- Machine Learning algorithms

- Neural Networks

- Computer Graphics

- Data Transformations

- Scientific Computing

Almost every ML model internally uses matrices and vectors.

## 1. Dot Product
- Mathematical Meaning

- The dot product is a way to multiply two vectors and get a single number (scalar).

- Formula:

- If
  - A = [a₁, a₂, a₃]
  - B = [b₁, b₂, b₃]

- Then:

  -  A · B = a₁b₁ + a₂b₂ + a₃b₃

- NumPy Function
   - np.dot(a, b)

In [1]:
# Example: Vector Dot Product
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)
print(result)

32


In [2]:
# Dot Product with Matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


- Important Point

   - For vectors → scalar

   - For matrices → matrix multiplication

### 2. Matrix Multiplication (@ Operator)
- Matrix multiplication combines rows of first matrix with columns of second matrix.
  - Rule

     - If:

        - A shape → (m, n)
        - B shape → (n, p)


     - Then result shape → (m, p)

- NumPy Syntax
   - A @ B


- OR

   - np.matmul(A, B)

In [3]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

print(A @ B)

[[ 4  4]
 [10  8]]


- Difference: * vs @
| Operator | Meaning                     |
| -------- | --------------------------- |
| `*`      | Element-wise multiplication |
| `@`      | Matrix multiplication       |

### 3. Cross Product
- The cross product is defined only for 3-dimensional vectors and returns a vector perpendicular to both input vectors.

  - Mathematical Meaning

     - If:

        - A = [a₁, a₂, a₃]
        - B = [b₁, b₂, b₃]


     - Then:


- NumPy Function
   - np.cross(a, b)

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.cross(a, b))

[-3  6 -3]


- Use Cases

   - Physics (torque, force)

   - 3D geometry

   - Robotics

### 4. Determinant (linalg.det)
- The determinant is a single number calculated from a square matrix.

- It tells:

    - Whether matrix is invertible

    - Area / volume scaling

    - Linear dependency

- Rules

    - Determinant ≠ 0 → matrix is invertible

    - Determinant = 0 → matrix is singular

- NumPy Function
    - np.linalg.det(matrix)

In [5]:
A = np.array([[1, 2],
              [3, 4]])

print(np.linalg.det(A))

-2.0000000000000004


- Interpretation

   - Positive → preserves orientation

   - Negative → flips orientation

### 5. Inverse of a Matrix (linalg.inv)
- The inverse of a matrix undoes the matrix multiplication.

- If:

  - A × A⁻¹ = I
    - where I is identity matrix.

- Condition
    - Only square matrices with non-zero determinant have inverses.

- NumPy Function
   - np.linalg.inv(A)

In [6]:
A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


- Verification
  - print(A @ A_inv)
    - Output ≈ Identity matrix

### 6. Eigenvalues & Eigenvectors
- An eigenvector is a vector that does not change direction when a matrix is applied to it.

- Only its magnitude changes.

- Mathematical Equation
   - A v = λ v

- Where:

   - v → eigenvector

   - λ → eigenvalue

- NumPy Function
   - np.linalg.eig(A)

In [7]:
A = np.array([[2, 0],
              [0, 3]])

values, vectors = np.linalg.eig(A)

print(values)
print(vectors)

[2. 3.]
[[1. 0.]
 [0. 1.]]


- Importance

  - PCA (Principal Component Analysis)

  - Image compression

  - Stability analysis

  - Neural networks

### 7. Solve Linear Equations (linalg.solve)
- Problem Type

  - Solve:

    - AX = B

- NumPy Function
  - np.linalg.solve(A, B)

- Example

  - Solve:

    - 2x + y = 5
    - x + 3y = 6

- Step 1: Convert to matrix form

In [8]:
A = np.array([[2, 1],
              [1, 3]])

B = np.array([5, 6])

- Step 2: Solve

In [9]:
X = np.linalg.solve(A, B)
print(X)

[1.8 1.4]


- Why linalg.solve() Is Better Than Inverse

  - Faster

  - More accurate

  - Numerically stable