# Masking & Filtering in NumPy

- Masking and filtering allow you to select, modify, or remove elements from arrays based on conditions, without using loops.

- This concept is fundamental to:

   - Data cleaning

   - Feature selection

   - Conditional transformations

   - ML preprocessing

# What Is Masking?

- A mask is a Boolean array (True / False) that has the same shape as the original array.

   - True → keep / select the value

   - False → ignore / discard the value

- NumPy uses masks to perform fast, vectorized filtering.

# **1. Boolean Masks**
- How Boolean Masks Are Created

  - A Boolean mask is created using comparison operators:

| Operator | Meaning               |
| -------- | --------------------- |
| `>`      | greater than          |
| `<`      | less than             |
| `>=`     | greater than or equal |
| `<=`     | less than or equal    |
| `==`     | equal                 |
| `!=`     | not equal             |

In [1]:
# Example: Creating a Boolean Mask
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

mask = arr > 30
print(mask)

[False False False  True  True]


- Each element is checked individually
- Result is a Boolean array

- **Using Mask to Filter Data**

In [2]:
filtered = arr[arr > 30]
print(filtered)  #Only values where condition is True are selected

[40 50]


- **Why Boolean Masking Is Powerful**

   - No loops

   - Very fast

   - Easy to read

   - Memory efficient

# **2. Filtering Based on Conditions**

- Single Condition Filtering

In [3]:
arr = np.array([5, 15, 25, 35, 45])

result = arr[arr >= 25]
print(result)

[25 35 45]


- **Multiple Conditions Filtering**

  - Use logical operators
| Operator | Meaning |    |
| -------- | ------- | -- |
| `&`      | AND     |    |
| `        | `       | OR |
| `~`      | NOT     |    |

- Always use parentheses.

In [4]:
# Example: AND Condition
arr = np.array([10, 20, 30, 40, 50])

result = arr[(arr > 20) & (arr < 50)]
print(result)

[30 40]


In [5]:
# Example: OR Condition
result = arr[(arr < 20) | (arr > 40)]
print(result)

[10 50]


In [6]:
# Example: NOT Condition
result = arr[~(arr == 30)]
print(result)

[10 20 40 50]


# **Masking in 2D Arrays**

In [7]:
# Example: Filter Values from Matrix
mat = np.array([[10, 25, 30],
                [40, 15, 50]])

mask = mat > 30
print(mask)

[[False False False]
 [ True False  True]]


- Selecting Values

In [8]:
print(mat[mat > 30])

[40 50]


- Modifying Values Using Mask

In [10]:
mat[mat < 20] = 0
print(mat)

# Values less than 20 replaced with 0

[[ 0 25 30]
 [40  0 50]]


# **3. np.where(condition, x, y)**

- np.where() works like a vectorized IF-ELSE statement.

  - If condition is True → take x  
  - If condition is False → take y

- Syntax
  - np.where(condition, x, y)

In [11]:
# Example 1: Replace Values Conditionally
arr = np.array([10, 25, 30, 45])

result = np.where(arr > 30, 1, 0)
print(result)

[0 0 0 1]


In [12]:
# Example 2: Conditional Transformation
arr = np.array([100, 200, 300])

result = np.where(arr > 150, arr * 2, arr / 2)
print(result)

[ 50. 400. 600.]


In [13]:
# Example 3: np.where() for Filtering Indices
arr = np.array([5, 15, 25, 35])

indices = np.where(arr > 20)
print(indices)

(array([2, 3]),)


**Difference: Masking vs np.where()**
| Feature         | Boolean Mask | np.where |
| --------------- | ------------ | -------- |
| Filtering       | Yes          | No       |
| Replacement     | Yes          | Yes      |
| IF-ELSE logic   | Limited      | Full     |
| Returns indices | No           | Yes      |