# What are Mathematical Functions in NumPy?
- NumPy mathematical functions are built-in optimized functions that perform:

   - Statistical calculations

   - Mathematical transformations

   - Scientific operations , on NumPy arrays efficiently and accurately.

- These functions work in a vectorized manner, meaning they operate on entire arrays at once.

# 1. Statistical Functions

- 1.1 sum()
  - Calculates the total sum of all elements in an array.

- Syntax
  - np.sum(array, axis=None)

In [4]:
import numpy as np
a = np.array([10, 20, 30, 40])
print(np.sum(a))

100


In [5]:
# 2D Example with axis
b = np.array([[1,2,3],
              [4,5,6]])

print(np.sum(b, axis=0))  # column sum
print(np.sum(b, axis=1))  # row sum

[5 7 9]
[ 6 15]


- 1.2 mean()
  - Calculates the average value.

- Formula
   - mean = sum of values / total number of values

In [7]:
print(np.mean(a))

25.0


- 1.3 median()
  - Returns the middle value after sorting the data.

- Rules

   - Odd count → middle element

   - Even count → average of two middle values

In [8]:
c = np.array([10, 50, 20, 40, 30])

print(np.median(c))

30.0


- 1.4 std() – Standard Deviation
   - Measures how spread out the values are from the mean.

- Concept

   - Small std → values are close to mean

   - Large std → values are widely spread

In [9]:
print(np.std(a))

11.180339887498949


- 1.5 var() – Variance
   - Variance is the square of standard deviation.

- Formula
   - variance = std²

In [10]:
print(np.var(a))

125.0


# 2. Minimum & Maximum Functions

- 2.1 max() and min()
    - Returns the largest and smallest element.

In [11]:
print(np.max(a))
print(np.min(a))

40
10


- 2.2 argmax() and argmin()
   - Returns the index position of the maximum or minimum value

In [12]:
d = np.array([10, 25, 5, 40])

print(np.argmax(d))
print(np.argmin(d))

3
2


# 3. Power & Logarithmic Functions

- 3.1 sqrt()
  - Calculates square root of each element.

In [13]:
x = np.array([4, 9, 16])

print(np.sqrt(x))

[2. 3. 4.]


- 3.2 power()
  - Raises each element to a given power.

In [14]:
print(np.power(x, 2))

[ 16  81 256]


- 3.3 exp()
   - Calculates e raised to power x.

In [15]:
print(np.exp([1, 2, 3]))

[ 2.71828183  7.3890561  20.08553692]


- 3.4 log() (Natural Log)
  - Computes log base e.

In [16]:
print(np.log([1, np.e, 10]))

[0.         1.         2.30258509]


- 3.5 log10()
  - Computes log base 10.

In [17]:
print(np.log10([1, 10, 100]))

[0. 1. 2.]


- Log functions do not accept zero or negative values.

# 4. Trigonometric Functions
- IMPORTANT RULE

   - NumPy trigonometric functions use radians, not degrees.

- Common Trigonometric Functions
| Function | Meaning         |
| -------- | --------------- |
| sin()    | Sine            |
| cos()    | Cosine          |
| tan()    | Tangent         |
| arcsin() | Inverse sine    |
| arccos() | Inverse cosine  |
| arctan() | Inverse tangent |

In [18]:
angles = np.array([0, np.pi/2, np.pi])

print(np.sin(angles))
print(np.cos(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [19]:
deg = np.array([0, 30, 90])
rad = np.deg2rad(deg)

print(np.sin(rad))

[0.  0.5 1. ]


# 5. Rounding Functions

- 5.1 floor()
  - Rounds down to nearest integer.

In [20]:
a = np.array([2.9, 3.1, -2.7])

print(np.floor(a))

[ 2.  3. -3.]


- 5.2 ceil()
  - mRounds up to nearest integer.

In [23]:
print(np.ceil(a))

[ 3.  4. -2.]


- 5.3 round()
  - Rounds to nearest value.

In [24]:
b = np.array([1.45, 1.55])

print(np.round(b))

[1. 2.]


In [25]:
# Decimal Places
print(np.round([1.2345, 2.6789], 2))


[1.23 2.68]


- 5.4 truncate()
   - Removes decimal part without rounding.

In [26]:
print(np.trunc(a))

[ 2.  3. -2.]


# Complete Summary Table
| Category     | Functions                    |
| ------------ | ---------------------------- |
| Statistics   | sum, mean, median, std, var  |
| Min/Max      | max, min, argmax, argmin     |
| Power/Log    | sqrt, power, exp, log, log10 |
| Trigonometry | sin, cos, tan                |
| Rounding     | floor, ceil, round, truncate |

In [2]:
import numpy as np
a = np.array([14, 54, -34, 56, -12, 23])
print(a + 21)
print(a - 20)
print(a * 3)
print(a / 5)

[ 35  75 -13  77   9  44]
[ -6  34 -54  36 -32   3]
[  42  162 -102  168  -36   69]
[ 2.8 10.8 -6.8 11.2 -2.4  4.6]
