In [1]:
import numpy as np

In [2]:
arr1 = np.array([[3,4,6],[5,7,4]])
print(arr1)

[[3 4 6]
 [5 7 4]]


- Attributes of array (Properties of array)

In [4]:
print("Shape",arr1.shape)
print("Size",arr1.size)
print("Dtype",arr1.dtype)
print("N Dimensions",arr1.ndim)

Shape (2, 3)
Size 6
Dtype int64
N Dimensions 2


In [5]:
arr2 = np.array([
    [
        [5,7,8],
        [4,6,7],
        [7,4,7]
    ],
    [
        [5,7,8],
        [4,6,7],
        [7,4,7]
            
        ]
])

In [6]:
print(arr2)

[[[5 7 8]
  [4 6 7]
  [7 4 7]]

 [[5 7 8]
  [4 6 7]
  [7 4 7]]]


In [7]:
print("Shape",arr2.shape)
print("Size",arr2.size)
print("Dtype",arr2.dtype)
print("N Dimensions",arr2.ndim)

Shape (2, 3, 3)
Size 18
Dtype int64
N Dimensions 3


In [8]:
arr4 = np.array([
    [
        [
            [4,5,6],
            [6,7,8]
        ]
    ],
    [
        [
            [6,7,4],
            [8,4,7]
        ]
    ],
])

In [9]:
print(arr4)

[[[[4 5 6]
   [6 7 8]]]


 [[[6 7 4]
   [8 4 7]]]]


In [10]:
print("Shape",arr4.shape)
print("Size",arr4.size)
print("Dtype",arr4.dtype)
print("N Dimensions",arr4.ndim)

Shape (2, 1, 2, 3)
Size 12
Dtype int64
N Dimensions 4


- Array initialization

In [14]:
zero_array = np.zeros((3,4)) # all elements will be zero.
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
print(np.zeros(5))
print(np.zeros((2,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
ones_array = np.ones((5,4)) # all elements will be 1.
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
print(np.ones(4))
print(np.ones((3,2)))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
full_arr = np.full((2,3),12) # full array: all elements will be same based on given values.
print(full_arr)

[[12 12 12]
 [12 12 12]]


In [18]:
id_arr = np.eye(4) # Identity matrix : Diagonal element values will b 1 and all other element's will be zero.
print(id_arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
print(np.empty(3)) # empty array : 

[0.00000000e+000 0.00000000e+000 9.07652206e+223]


In [20]:
print(np.arange(2,10)) # evenly spaced array: element are evenly spaced based on step values.

[2 3 4 5 6 7 8 9]


In [21]:
print(np.arange(2,10,2))

[2 4 6 8]


In [22]:
arrL = np.linspace(0,10,20) # specified number of equaly spaced values between a range.
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [11]:
arr = np.random.rand(10) #random values array - float
print(arr)

[0.9434317  0.67974036 0.15421631 0.36127104 0.36216406 0.10293023
 0.74500255 0.60205878 0.2449357  0.05209053]


In [24]:
arr = np.random.rand(3,4)
arr

array([[0.00207354, 0.32246694, 0.89169591, 0.10482059],
       [0.0607768 , 0.24049282, 0.53314055, 0.87037799],
       [0.8202422 , 0.26117966, 0.49067823, 0.04968681]])

In [28]:
random_int = np.random.randint(1,10) # random value - int
print(random_int)

4


In [29]:
random_int = np.random.randint(1,10,4) # random values  based on given number(4) - int 
print(random_int)

[6 4 5 9]


In [26]:
random_int = np.random.randint(1,100,(3,4)) # random values - int
print(random_int)

[[48 93 91 73]
 [36 60 49 61]
 [94  3 74 27]]


- Array indexing

In [37]:
ind_arr1 = np.array([4,7,73,78])
print(ind_arr1[2])

73


In [38]:
ind_arr2 = np.array([4,7,73,78])
print(ind_arr2[-3])

7


In [39]:
ind_arr3 = np.array([[4,7,73,78],[6,7,8,5]])
print(ind_arr3[1][2])

8


In [40]:
print(ind_arr1[:])

[ 4  7 73 78]


In [41]:
print(ind_arr1[::])

[ 4  7 73 78]


In [42]:
print(ind_arr1[1:3])

[ 7 73]


In [43]:
print(ind_arr1[-2:])

[73 78]


In [44]:
print(ind_arr1[1::2])

[ 7 78]


- Indexing in 2D array

In [46]:
ind_arr4 = np.array([[4,7,73,78],[6,7,8,5]])
print(ind_arr4[0])
print(ind_arr4[1])

[ 4  7 73 78]
[6 7 8 5]


In [47]:
print(ind_arr4[0][2])

73


In [48]:
print(ind_arr4[0][1])
print(ind_arr4[1][0])

7
6


In [51]:
ind_arr5 = np.array([[4,7,73,78],[6,7,8,5]]) # based on columns
print(ind_arr5[:,0])
print(ind_arr5[:,1])
print(ind_arr5[:,3])

[4 6]
[7 7]
[78  5]


In [23]:
print(arr_2d[1][2])

6


In [3]:
# 3d indexing
arr = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [10]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
print(arr.shape) #(array number, number of rows in per array, number of column in per array)

(2, 2, 3)


In [5]:
print(arr[0,0,0]) #[array number in array, no of row , no of column]

1


In [7]:
print(arr[0,1,2])

6


In [9]:
print(arr[1,1,1])

11


In [11]:
print(arr[0])

[[1 2 3]
 [4 5 6]]


In [12]:
print(arr[1])

[[ 7  8  9]
 [10 11 12]]


In [14]:
print(arr[::,0])

[[1 2 3]
 [7 8 9]]


In [19]:
print(arr[::])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
print(arr[::,1])

[[ 4  5  6]
 [10 11 12]]


In [16]:
print(arr[::,1,1])

[ 5 11]


In [18]:
print(arr[::,0])

[[1 2 3]
 [7 8 9]]


In [20]:
print(arr[::,1:])

[[[ 4  5  6]]

 [[10 11 12]]]


In [22]:
print(arr[::,1:1])

[]


In [23]:
print(arr[::,0:1])

[[[1 2 3]]

 [[7 8 9]]]


In [24]:
print(arr[::,0:2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
