# What is Python Library?
- A python library is a group of interconnected modules. it contains code bundles that can be reused in different programs

- Python Libraries 
  - Various python libraries make programming easier.
     - Numpy
     - Pandas
     - Scipy
     - Matplotlib
     - Scikit-learn
     - Seaborn
        - These were some commonly used libraries are:

In [1]:
import numpy

In [2]:
dir(numpy)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmi

In [3]:
import pandas
dir(pandas)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annota

In [4]:
import matplotlib
dir(matplotlib)

['ExecutableNotFoundError',
 'MatplotlibDeprecationWarning',
 'MutableMapping',
 'Parameter',
 'Path',
 'RcParams',
 '_ExecInfo',
 '_VersionInfo',
 '__all__',
 '__bibtex__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_add_data_doc',
 '_api',
 '_c_internal_utils',
 '_check_versions',
 '_cm',
 '_cm_bivar',
 '_cm_listed',
 '_cm_multivar',
 '_color_data',
 '_deprecated_ignore_map',
 '_deprecated_map',
 '_deprecated_remain_as_none',
 '_docstring',
 '_ensure_handler',
 '_enums',
 '_fontconfig_pattern',
 '_get_config_or_cache_dir',
 '_get_executable_info',
 '_get_ssl_context',
 '_get_version',
 '_get_xdg_cache_dir',
 '_get_xdg_config_dir',
 '_image',
 '_init_tests',
 '_label_from_arg',
 '_log',
 '_logged_cached',
 '_open_file_or_url',
 '_parse_to_version_info',
 '_path',
 '_preprocess_data',
 '_rc_params_in_file',
 '_replacer',
 '_val_or_rc',
 '_version',
 'artist',
 'atexit',
 'backends',
 '

In [5]:
import seaborn
dir(seaborn)

['FacetGrid',
 'JointGrid',
 'PairGrid',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_base',
 '_compat',
 '_core',
 '_docstrings',
 '_orig_rc_params',
 '_statistics',
 '_stats',
 'algorithms',
 'axes_style',
 'axisgrid',
 'barplot',
 'blend_palette',
 'boxenplot',
 'boxplot',
 'categorical',
 'catplot',
 'choose_colorbrewer_palette',
 'choose_cubehelix_palette',
 'choose_dark_palette',
 'choose_diverging_palette',
 'choose_light_palette',
 'clustermap',
 'cm',
 'color_palette',
 'colors',
 'countplot',
 'crayon_palette',
 'crayons',
 'cubehelix_palette',
 'dark_palette',
 'desaturate',
 'despine',
 'displot',
 'distplot',
 'distributions',
 'diverging_palette',
 'dogplot',
 'ecdfplot',
 'external',
 'get_data_home',
 'get_dataset_names',
 'heatmap',
 'histplot',
 'hls_palette',
 'husl_palette',
 'jointplot',
 'kdeplot',
 'light_palette',
 'lineplot',
 'lmplot',
 'load_dataset',
 'matrix

In [7]:
import scipy
dir(scipy)

['LowLevelCallable',
 '__version__',
 'cluster',
 'constants',
 'datasets',
 'differentiate',
 'fft',
 'fftpack',
 'integrate',
 'interpolate',
 'io',
 'linalg',
 'ndimage',
 'odr',
 'optimize',
 'show_config',
 'signal',
 'sparse',
 'spatial',
 'special',
 'stats',
 'test']

# Benefits of Python Libraries 
- Easy to learn
- Open source
- Efficient and multi-platform support
- Huge collection of function and modules
- Big open-source community
- Integrates well eith enterprise apps and systems

# Numpy
- Numpy is a library used for mathematical computations with multi-dimensional numerical data
  > Numpy is a low-level library written in C and FORTRAN for high-level mathematical functions. Numpy cleverly overcomes the problem of running slower algorithm in Python by using multidimensional arrays and functions that operate on arrays. Any algorithm can be expressed as a function on arrays, which allows the algorithms to be executed quickly and efficienly.

# Pandas
- Pandas consist of a variety of analysis tools and configuration high-level data structures.

# Scipy
- Scientific Python is an open-source high-level scintific computation package. This library is based on a Numpy extension.

# Matplotlib
- It is also an open-source library that plots high-definition figures such as pie charts, histograms etc.

# Scikit - learn
- The library contains a lot of efficient tools for machine learning and statistical modeling including classification, regression, clustering and dimensinality reduction.

# What is an array?
- An array is a central data structure of the Numpy libray.
- It is a grid of homogeneous values (same data type).
- The rank of the array is the number of dimensions
- The array object in NumPy is called ndarray(n dimensional array).

# Introduction to NumPy
- It is a python library used for working with arrays
- It consists of multidimensional array of objects and a collection them.
- It conduts mathematical and logical operations on arrays.

# Advantages of NumPy
- It provides an array objects that is faster than traditional Python lists.
- It provides supporting functions.
- Arrays are frequently used in data science.

In [1]:
# Imorting numpy
import numpy as np
arr = np.array({1,2,3,4})
arr

array({1, 2, 3, 4}, dtype=object)

In [11]:
print(np.__version__)

2.1.3


In [12]:
np.version

<module 'numpy.version' from 'C:\\Users\\HP\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [13]:
type(arr)

numpy.ndarray

In [14]:
arr1 = np.array([4,6,3,8,8])
arr1

array([4, 6, 3, 8, 8])

In [15]:
arr2 = np.array([4,"string", 80, None])
arr2

array([4, 'string', 80, None], dtype=object)

- Creating a Zero Dimensional array
  - It has only one value.

In [16]:
arr3 = np.array(85)
print(arr3)

85


- Creating 1D array

In [17]:
arr4 = np.array([2,5,7,3,7,])
arr4

array([2, 5, 7, 3, 7])

- Creating 2D array

In [21]:
arr5 = np.array([[9,5,6],[3,7,8]])
print(arr5)

[[9 5 6]
 [3 7 8]]


- Creating 3D array

In [22]:
arr6 = np.array([[[9,5,6],[3,7,8],[7,2,5]]])
print(arr6)

[[[9 5 6]
  [3 7 8]
  [7 2 5]]]


In [23]:
arr7 = np.array([[[9,5,6],[3,7,8],[7,2,5],[8,3,4]]])
print(arr7)

[[[9 5 6]
  [3 7 8]
  [7 2 5]
  [8 3 4]]]


- Creating 4D array

In [24]:
arr8 = np.array([[[[9,5,6],[3,7,8],[7,2,5],[8,3,4],[8,8,4]]]])
print(arr8)

[[[[9 5 6]
   [3 7 8]
   [7 2 5]
   [8 3 4]
   [8 8 4]]]]


In [25]:
arr8.ndim

4

In [39]:
arr9 = np.array([[[4,4,5],[5,8,2]],[[4,8,9],[2,5,7]]])

In [40]:
print(arr9)

[[[4 4 5]
  [5 8 2]]

 [[4 8 9]
  [2 5 7]]]


In [2]:
import numpy as np
arr10 = np.array([
    [
        [
            [4,4,5],
            [5,8,2],
            [4,8,9]
        ]
    ],
    [
        [
            [8,6,3],
            [1,2,3],
            [2,5,7]
        ]
    ],
    [
        [
            [8,9,5],
            [6,5,4],
            [1,2,3]
        ]
    ]])

In [3]:
print(arr10)

[[[[4 4 5]
   [5 8 2]
   [4 8 9]]]


 [[[8 6 3]
   [1 2 3]
   [2 5 7]]]


 [[[8 9 5]
   [6 5 4]
   [1 2 3]]]]


In [4]:
arr10.ndim

4

In [ ]:
print(arr10)

- Creating 5D array

In [5]:
arr11 = np.array([
    [
        [
            [
                [4,5,7],
                [6,8,2]
                ]
            ]
        ],
        [
            [
                [
                    [5,7,3],
                    [8,2,3]
                ]
            ]
        ],
        [
            [
                [
                    [1,2,3],
                    [2,5,5]
                ]
            ]
        ]
    ])

In [6]:
print(arr11)

[[[[[4 5 7]
    [6 8 2]]]]



 [[[[5 7 3]
    [8 2 3]]]]



 [[[[1 2 3]
    [2 5 5]]]]]


In [7]:
arr11.ndim

5

In [2]:
import numpy as np

a = np.random.rand(5)
print(a)

[0.64782316 0.28818611 0.20332362 0.97926551 0.68833089]


In [3]:
b = np.random.rand(3, 4)
print(b)

[[0.05494705 0.98260281 0.38095675 0.80593762]
 [0.45775592 0.85540869 0.49394622 0.46931667]
 [0.92799141 0.18284238 0.72629158 0.58186903]]


In [4]:
c = np.random.rand(2, 2, 3)
print(c)

[[[2.23049116e-01 8.69819644e-01 4.93123924e-02]
  [1.94129989e-01 1.43469979e-01 7.84961999e-01]]

 [[7.45123253e-01 1.37994984e-01 4.80200376e-03]
  [4.95240251e-01 5.86950518e-04 9.18668693e-01]]]


In [5]:
a = np.random.randn(5)
print(a)

[ 0.69150388 -0.2667534  -0.78899155 -0.92064463 -0.35432729]


In [6]:
b = np.random.randn(3, 3)
print(b)


[[ 0.98418968 -0.64413494 -0.85282008]
 [ 0.41956107  0.91976082  0.09066713]
 [-0.30701042  1.49483569 -1.6364103 ]]


In [7]:
print(np.random.randint(1, 10))

8


In [8]:
a = np.random.randint(10, 50, size=5)
print(a)

[36 30 42 24 34]


In [9]:
b = np.random.randint(0, 100, size=(3, 4))
print(b)

[[20  8 70 89]
 [77 16 46 85]
 [80 51 75 43]]


In [10]:
a = np.random.random(5)
print(a)

[0.15190145 0.68261663 0.2791843  0.06019149 0.53092274]


In [11]:
a = np.array([10, 20, 30, 40])

print(np.random.choice(a))

20


In [12]:
print(np.random.choice(a, size=3))

[10 40 10]


In [13]:
print(np.random.choice(a, size=3, replace=False))

[20 10 30]


In [14]:
print(np.random.choice(a, size=3, replace=False))

[40 30 20]


In [15]:
print(np.random.choice(a, size=5, p=[0.1, 0.2, 0.3, 0.4]))

[30 30 30 40 40]


In [20]:
np.random.seed(42)
print(np.random.rand(3))

np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]


- Array Reverse

In [24]:
arr = np.array([8,5,4,3,1,7,6,9])
arr

array([8, 5, 4, 3, 1, 7, 6, 9])

In [25]:
arr[::-1]

array([9, 6, 7, 1, 3, 4, 5, 8])

In [26]:
arr.shape = (2,4) 
print(arr)

[[8 5 4 3]
 [1 7 6 9]]


In [30]:
print(arr[0][::-1])
print(arr[1][::-1])

[3 4 5 8]
[9 6 7 1]


In [32]:
arr.shape = (2,2,2) 
print(arr)

[[[8 5]
  [4 3]]

 [[1 7]
  [6 9]]]


In [34]:
print(arr[0][0][::-1])
print(arr[0][1][::-1])
print(arr[1][0][::-1])
print(arr[1][1][::-1])

[5 8]
[3 4]
[7 1]
[9 6]


In [35]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)
print(result)

32


In [36]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.dot(A, B))

[[19 22]
 [43 50]]


In [37]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

print(A @ B)

[[ 4  4]
 [10  8]]


In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.cross(a, b))

[-3  6 -3]


In [39]:
A = np.array([[1, 2],
              [3, 4]])

print(np.linalg.det(A))

-2.0000000000000004


In [40]:
A = np.array([[1, 2],
              [3, 4]])

A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:
print(A @ A_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [43]:
A = np.array([[2, 1],
              [1, 3]])

B = np.array([5, 6])
X = np.linalg.solve(A, B)
print(X)

[1.8 1.4]
