# What is the NumPy Random Module?
- The NumPy random module is used to generate random numbers and random arrays for:

    - Simulations

    - Machine learning model initialization

    - Data sampling

    - Statistical experiments

    - Testing and debugging

 Random numbers generated by NumPy are pseudo-random, meaning they are generated by mathematical algorithms.

## Why Random Numbers Are Important

    - ML algorithms start with random weights

    - Train-test split requires randomness

    - Monte Carlo simulations

    - Random sampling of data

### 1. np.random.rand()
- Generates random numbers from a uniform distribution in the range [0, 1).

- Syntax
   - np.random.rand(d0, d1, d2, ...)


Each argument represents a dimension size.

- Key Properties

    - Values are ≥ 0 and < 1

    - Uniform distribution

    - Output is a NumPy array

In [1]:
# Example: 1D Array
import numpy as np

a = np.random.rand(5)
print(a)

[0.90540031 0.57812719 0.60255562 0.4325957  0.56865414]


In [2]:
# Example: 2D Array
b = np.random.rand(3, 4)
print(b)

[[0.61590371 0.76071078 0.80611992 0.88618565]
 [0.35323692 0.88562139 0.93822604 0.86771528]
 [0.19651457 0.61741123 0.39503989 0.76930569]]


In [3]:
# Example: 3D Array
c = np.random.rand(2, 2, 3)
print(c)

[[[0.94242819 0.62033509 0.01717276]
  [0.92825375 0.28221247 0.1465819 ]]

 [[0.11051982 0.96949627 0.31508818]
  [0.32423122 0.78057787 0.19033619]]]


### 2. np.random.randn()
- Generates random numbers from a standard normal distribution
- (mean = 0, standard deviation = 1).

    - Difference from rand()
| rand()               | randn()                     |
| -------------------- | --------------------------- |
| Uniform distribution | Normal distribution         |
| Range: [0,1)         | Range: (−∞, +∞)             |
| No negative values   | Can produce negative values |

In [4]:
a = np.random.randn(5)
print(a)

[ 0.02334886 -0.55134177 -0.10347498 -0.6553303   0.66439053]


In [5]:
# 2D Example
b = np.random.randn(3, 3)
print(b)

[[ 0.48675717  0.97112291  1.81266886]
 [ 0.68274103 -0.430337    0.64991486]
 [ 0.14572566 -0.5182375  -0.35014749]]


### 3. np.random.randint()
- Generates random integers within a specified range.

- Syntax
   - np.random.randint(low, high=None, size=None)

- Important Rules

   - low is inclusive

   - high is exclusive

   - Can generate single value or array

- Single Integer

In [6]:
print(np.random.randint(1, 10))

2


In [7]:
# 1D Array
a = np.random.randint(10, 50, size=5)
print(a)

[31 45 30 19 32]


In [8]:
# 2D Matrix
b = np.random.randint(0, 100, size=(3, 4))
print(b)

[[ 1 65 76 57]
 [ 9 30 60 24]
 [34 74 59 17]]


### 4. np.random.random()
- Generates random numbers from uniform distribution [0,1).

   - Difference from rand()
| random()            | rand()                     |
| ------------------- | -------------------------- |
| Accepts tuple shape | Accepts separate arguments |


In [9]:
a = np.random.random(5)
print(a)

[0.86535755 0.32395677 0.28099055 0.90602589 0.2030483 ]


In [10]:
# 2D Example
b = np.random.random((3, 3))
print(b)

[[0.05070966 0.49357296 0.94987271]
 [0.37536615 0.09564836 0.31109789]
 [0.91734389 0.53253921 0.17542997]]


### 5. np.random.choice()
- Randomly selects elements from a given array or range.

- Syntax
    - np.random.choice(a, size=None, replace=True, p=None)

- Parameters Explained

    - a → input array or integer range

    - size → output shape

    - replace → allow repetition or not

    - p → probability distribution

- Example: Choose from array

In [11]:
a = np.array([10, 20, 30, 40])

print(np.random.choice(a))

30


- Choose multiple values

In [12]:
print(np.random.choice(a, size=3))

[30 30 20]


- Without replacement

In [13]:
print(np.random.choice(a, size=3, replace=False))

[10 20 30]


- With probabilities

In [14]:
print(np.random.choice(a, size=5, p=[0.1, 0.2, 0.3, 0.4]))

[40 20 30 20 40]


### 6. np.random.seed()
- Sets the seed value to make random numbers reproducible.

- Why It Is Important

   - Debugging

   - Research experiments

   - Model reproducibility

In [15]:
np.random.seed(42)
print(np.random.rand(3))

np.random.seed(42)
print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]


- Output will be exactly the same.

### 7. Creating Random Matrices

- Uniform Random Matrix

In [18]:
matrix = np.random.rand(3, 4)
print(matrix)

[[0.51423444 0.59241457 0.04645041 0.60754485]
 [0.17052412 0.06505159 0.94888554 0.96563203]
 [0.80839735 0.30461377 0.09767211 0.68423303]]


- Normal Distribution Matrix

In [20]:
matrix = np.random.randn(3, 4)
print(matrix)

[[-1.00908534 -1.58329421  0.77370042 -0.53814166]
 [-1.3466781  -0.88059127 -1.1305523   0.13442888]
 [ 0.58212279  0.88774846  0.89433233  0.7549978 ]]


- Integer Random Matrix

In [22]:
matrix = np.random.randint(1, 100, size=(3, 4))
print(matrix)

[[88 37 99 44]
 [86 91 35 65]
 [99 47 78  3]]


- Binary Random Matrix

In [23]:
matrix = np.random.randint(0, 2, size=(4, 4))
print(matrix)

[[0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [1 1 0 0]]


- Probability-Based Matrix

In [24]:
matrix = np.random.choice([0,1], size=(3,3), p=[0.7, 0.3])
print(matrix)

[[0 0 0]
 [0 1 0]
 [0 1 0]]
