# What is a NumPy Array (ndarray)?
- A NumPy Array is a special data structure provided by NumPy, called ndarray (N-Dimensional Array), which is used to store multiple values of the same data type in a continuous block of memory.


- Meaning of "ndarray"

    - n → number of dimensions
    - d → dimensional
    - array → collection of elements


- So, ndarray means:
  - An array that can have 1 or more dimensions.

# Key Characteristics of NumPy Arrays
1.	Stores elements of same data type
2.	Faster than Python lists
3.	Supports multi-dimensional data
4.	Allows vectorized operations
5.	Uses less memory


In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)
print(type(arr))


[10 20 30 40]
<class 'numpy.ndarray'>


# Difference Between Python List and NumPy Array
| Feature         | Python List   | NumPy Array |
| --------------- | ------------- | ----------- |
| Data Type       | Mixed allowed | Same only   |
| Speed           | Slow          | Fast        |
| Memory          | More          | Less        |
| Math Operations | Loop needed   | Direct      |
| Dimensions      | Limited       | Multiple    |


# Creating NumPy Arrays 

- There are three major ways to create NumPy arrays:

   - From Lists

   - From Tuples

   - Using Built-in Functions

# A) Creating NumPy Array from Lists

1. Dimensional Array from List
- A 1D array is a linear array containing elements in a single row.

In [2]:
list_data = [1, 2, 3, 4, 5]
arr = np.array(list_data)

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


- Important 

  - Python list → converted into NumPy array

  - Data type is automatically detected

In [3]:
#Check Data Type
print(arr.dtype)

int64


2. Dimensional Array from List
- A 2D array is like a matrix (rows and columns).

In [4]:
list_2d = [[1,2,3],
           [4,5,6],
           [7,8,9]]

arr2d = np.array(list_2d)

print(arr2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Check Dimensions
print(arr2d.ndim)    # Number of dimensions
print(arr2d.shape)  # Rows and columns

2
(3, 3)


3. Mixed Data in List
- NumPy converts all elements to a common data type
- Result becomes float

# B) Creating NumPy Array from Tuples
- A tuple is similar to a list but immutable.
- NumPy can convert tuples into arrays easily.

In [6]:
# 1D Array
import numpy as np

tuple_data = (10, 20, 30, 40)
arr = np.array(tuple_data)

print(arr)

[10 20 30 40]


In [7]:
# 2D Array from Tuple
tuple_2d = ((1,2,3),
            (4,5,6))

arr2 = np.array(tuple_2d)
print(arr2)

[[1 2 3]
 [4 5 6]]


# Why Use Tuples?
- Fixed data
- Slightly faster creation
- Useful in constant datasets

# C) Creating NumPy Arrays Using Built-in Functions
- These functions help create arrays without manually writing elements.

1. np.zeros()
- Creates an array filled with 0.

In [8]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [9]:
# 2D Zeros Array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

2. np.ones()
- Creates an array filled with 1.

In [10]:
np.ones(4)

array([1., 1., 1., 1.])

In [11]:
# 2D Ones Array
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

3. np.full()
- Creates array filled with a specific value.

In [12]:
np.full((3,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

4. np.empty()
- Creates array with random garbage values (uninitialized).

In [13]:
np.empty(4)
# Values are unpredictabl

array([1., 1., 1., 1.])

5. np.arange()
- Creates array with values in a range (similar to range()).
- Syntax
   - np.arange(start, stop, step)

In [14]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

6. np.linspace()
- Generates evenly spaced numbers between a range.

In [15]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

7. np.eye() (Identity Matrix)
- Creates an identity matrix.

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- Important Observations

   - NumPy arrays store same type of data

   - Built-in functions save time

   - Arrays are memory efficient

   - Multi-dimensional arrays are easy