# NumPy I/O Operations

NumPy provides built-in functions to:

  - Save arrays to files

  - Load arrays from files

  - Handle binary files and text files

  - Work with missing values


## Why NumPy I/O Is Needed

When working with:

- Large datasets

- ML training data

- mScientific results

- Intermediate array outputs

You must store arrays permanently instead of recalculating every time.

### 1. np.save() – Save Array in Binary Format
- Purpose
   - Saves a single NumPy array in .npy format (binary).

- Key Features

   - Fast

   - Preserves dtype, shape, dimensions

   - File extension automatically becomes .npy

- Syntax
   - np.save(filename, array)

In [1]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

np.save("data", arr)
# Creates file → data.npy

### 2. np.load() – Load Array from .npy File
- Purpose
   - Loads an array saved using np.save().

- Syntax
   - np.load(filename)

In [3]:
loaded_arr = np.load("data.npy")
print(loaded_arr)
# Original array is fully restored

[[1 2 3]
 [4 5 6]]


- Important Note

   - Automatically detects shape and dtype

   - Works for .npy and .npz files

In [7]:
arr = np.array([[1.234, 2.345],
                [3.456, 4.567]])

np.savetxt("data.txt", arr, delimiter=",", fmt="%.2f")

- Limitations

   - Slower than binary

   - Loses dtype information

   - Best for sharing & viewing

### 4. np.loadtxt() – Load Data from Text File
- Purpose
   - Loads numeric data from a text file.

- Syntax
   - np.loadtxt(filename, delimiter=",")

In [8]:
arr = np.loadtxt("data.txt", delimiter=",")
print(arr)

[[1.23 2.35]
 [3.46 4.57]]


- Important Restrictions

  - All values must be numeric
 
  - Cannot handle missing values

### 5. np.genfromtxt() – Load Text with Missing Values
- Purpose
  - Loads data from text files with missing or invalid values.

- Why Needed
  - Real-world data often contains:

     - Missing entries

     - NaN values

     - Inconsistent rows

- Syntax
  - np.genfromtxt(filename, delimiter=",", filling_values=0)

- Advantages over loadtxt()
| Feature        | genfromtxt | loadtxt |
| -------------- | ---------- | ------- |
| Missing values | Yes        | No      |
| Robust         | High       | Low     |
| Speed          | Slower     | Faster  |

### 6. np.fromfile() – Read Raw Binary Data
- Purpose
   - Reads raw binary data directly from a file.

- Syntax
   - np.fromfile(filename, dtype, count=-1, sep="")

In [10]:
arr = np.array([1, 2, 3, 4], dtype=np.int32)
arr.tofile("binary.dat")

loaded = np.fromfile("binary.dat", dtype=np.int32)
print(loaded)

[1 2 3 4]


- Important Warning

  - No metadata (shape must be known)

  - Platform dependent

  - Use carefully

### Comparison Table
| Function       | File Type  | Preserves Shape | Handles Missing | Speed  |
| -------------- | ---------- | --------------- | --------------- | ------ |
| `save()`       | `.npy`     | Yes             | Yes             | Fast   |
| `load()`       | `.npy`     | Yes             | Yes             | Fast   |
| `savetxt()`    | Text       | No              | No              | Slow   |
| `loadtxt()`    | Text       | No              | No              | Medium |
| `genfromtxt()` | Text       | No              | Yes             | Slow   |
| `fromfile()`   | Raw Binary | No              | No              | Fast   |