# What is Shape Manipulation?
- Shape manipulation means changing the structure (dimensions and layout) of a NumPy array without changing the actual data values.

- Example:

  - Convert 1D → 2D

  - Convert matrix → vector

  - Add or remove dimensions

- Why Shape Manipulation is Needed

  - ML models require specific input shapes

  - Data visualization needs reshaping

  - Broadcasting requires compatible shapes

  - Image data needs dimensional control

# 1. reshape()
   - reshape() changes the shape (dimensions) of an array without changing the data.
- Syntax
   - array.reshape(new_shape)
 
- Important Rule
   - Total number of elements MUST remain the same


In [1]:
import numpy as np

a = np.array([1,2,3,4,5,6])

b = a.reshape(2,3) # (row, column)
print(b)

[[1 2 3]
 [4 5 6]]


In [2]:
# 2D to 3D Example
c = np.arange(12)
print(c.reshape(2,2,3)) #(array number, number of rows in per array, number of column in per array)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


- reshape() returns a VIEW (if possible)

  - This means:

      - Data is shared

      - Changing one may affect the other

# 2. reshape(-1)
- -1 tells NumPy:
   - “Automatically calculate this dimension for me”

In [3]:
a = np.array([[1,2,3],
              [4,5,6]])

print(a.reshape(-1))

[1 2 3 4 5 6]


- Use Cases

   - Convert multi-dimensional array into 1D

   - Prepare data for ML models

# 3. ravel()
- ravel() flattens a multi-dimensional array into 1D, returns a VIEW whenever possible.

- Syntax
   - array.ravel()

In [4]:
a = np.array([[1,2],
              [3,4]])

b = a.ravel()
print(b)

[1 2 3 4]


- Key Property

   - Shares memory

   - Faster than flatten()

In [5]:
b[0] = 100
print(a)

[[100   2]
 [  3   4]]


# 4. flatten()
- flatten() also converts array into 1D, but it always returns a COPY.

In [2]:
arr1 = np.array([
    [
        [23,4,5],
        [6,7,4]
    ],

    [
        [6,7,4],
        [8,1,2]
    ]
])

In [3]:
print(arr1.flatten())

[23  4  5  6  7  4  6  7  4  8  1  2]


In [4]:
print(arr1)

[[[23  4  5]
  [ 6  7  4]]

 [[ 6  7  4]
  [ 8  1  2]]]


In [6]:
a = np.array([[1,2],
              [3,4]])

b = a.flatten()
b[0] = 100

print(a)
print(b)

[[1 2]
 [3 4]]
[100   2   3   4]


- Difference from ravel()
| Feature           | ravel() | flatten() |
| ----------------- | ------- | --------- |
| Memory            | View    | Copy      |
| Speed             | Faster  | Slower    |
| Safe modification | ❌      | ✔         |


5. transpose()
- transpose() swaps rows and columns (axes).

- Syntax

   - array.transpose()

In [7]:
# 2D Example
a = np.array([[1,2,3],
              [4,5,6]])

print(a.transpose())

[[1 4]
 [2 5]
 [3 6]]


6. T Attribute
- T is a shortcut for transpose.

In [9]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


- Important Note

   - Works same as transpose()

   - Very commonly used in ML

# 7. squeeze()
 - Removes dimensions of size 1.

In [10]:
a = np.array([[[10, 20, 30]]])
print(a.shape)

b = np.squeeze(a)
print(b.shape)

(1, 1, 3)
(3,)


- Use Case

  - Remove unnecessary dimensions

  - Clean ML input/output shapes

# 8. expand_dims()
- Adds a new axis at a specified position.

- Syntax
   - np.expand_dims(array, axis)

In [11]:
a = np.array([1,2,3])

b = np.expand_dims(a, axis=0)
c = np.expand_dims(a, axis=1)

print(b.shape)
print(c.shape)

(1, 3)
(3, 1)


- Why Important

  - Required for broadcasting

  - Used before feeding data into ML models

- Complete Comparison Table
| Function      | Purpose            | View/Copy          |
| ------------- | ------------------ | ------------------ |
| reshape()     | Change shape       | View (if possible) |
| reshape(-1)   | Auto flatten       | View               |
| ravel()       | Flatten            | View               |
| flatten()     | Flatten            | Copy               |
| transpose()   | Swap axes          | View               |
| T             | Shortcut transpose | View               |
| squeeze()     | Remove axis of 1   | View               |
| expand_dims() | Add new axis       | View               |

In [1]:
import numpy as np
x = np.array([2,2,3,4])
print(x.shape)
print(x)
# (2,2) - - 2*2 = 4
# (2,3) - - 2*3 - 6
x.shape = (1,2,1,2) # 1*2*1*2 = 4

(4,)
[2 2 3 4]


In [6]:
x.shape=(2,2)
x

array([[2, 2],
       [3, 4]])

In [7]:
#2D
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr_2d.shape

(2, 3)

In [10]:
arr_2d.shape = (6)
arr_2d

array([1, 2, 3, 4, 5, 6])

In [15]:
arr_2d.shape = (2,3,1)
arr_2d

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [16]:
arr_2d.shape = (2,3,1,1)
arr_2d

array([[[[1]],

        [[2]],

        [[3]]],


       [[[4]],

        [[5]],

        [[6]]]])

In [11]:
arr5 = np.array([1,2,3,4,5,6,7,8])
print(arr5.shape)

(8,)


In [12]:
arr5.shape = (2,2,2) 
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
arr5.shape = (2,2,2,1) 
arr5

array([[[[1],
         [2]],

        [[3],
         [4]]],


       [[[5],
         [6]],

        [[7],
         [8]]]])

In [17]:
arr_n = np.array([1,2,3,4,5,6,7,8,9,7,6,4])
arr_n.shape

(12,)

In [18]:
arr_n.shape = (4,3)
arr_n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 6, 4]])

In [19]:
arr_n.shape = (2,2,3)
arr_n

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [7, 6, 4]]])

In [20]:
arr_n.shape = (2,2,3,1)
arr_n

array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]],


       [[[7],
         [8],
         [9]],

        [[7],
         [6],
         [4]]]])