# Sorting & Searching in NumPy

# Why Sorting & Searching are Needed

  - In real-world data:

  - Data is often unsorted

  - We need to rank values

  - We need to find positions of elements

  - We need to filter based on conditions

  - NumPy provides fast, vectorized, optimized functions for these tasks.

# PART 1: SORTING FUNCTIONS

1. sort()
 - np.sort() returns a sorted copy of the array without changing the original array.

 - Syntax
   - np.sort(array, axis=-1)
  
- Key Properties

   - Returns a new array

   - Original array remains unchanged

   - Sorting is done in ascending order by default

In [1]:
# Example: 1D Array
import numpy as np

a = np.array([40, 10, 30, 20])

sorted_a = np.sort(a)
print(sorted_a)
print(a)

[10 20 30 40]
[40 10 30 20]


In [2]:
# 2D Array Sorting
b = np.array([[3, 1, 2],
              [6, 4, 5]])

print(np.sort(b))        # sort along last axis (columns)
print(np.sort(b, axis=0)) # sort column-wise

[[1 2 3]
 [4 5 6]]
[[3 1 2]
 [6 4 5]]


- In-place Sorting
  - This modifies the original array.

In [3]:
a.sort()

2. argsort()
  - argsort() returns the indices that would sort the array, not the sorted values themselves.

- Why It Is Important

  - Used when:

     - You want to reorder another array

     - You want to track original positions

In [4]:
a = np.array([40, 10, 30, 20])

index = np.argsort(a)
print(index)

[1 3 2 0]


- Using argsort to Sort Another Array

In [5]:
names = np.array(["A", "B", "C", "D"])
scores = np.array([80, 95, 70, 90])

order = np.argsort(scores)
print(names[order])
print(scores[order])

['C' 'A' 'D' 'B']
[70 80 90 95]


3. lexsort() (Lexicographical Sort)
- lexsort() sorts data using multiple sorting keys.

- Sorting happens from last key to first key.

- Use Case

   - Sorting by multiple columns

   - Common in structured/tabular data

- Syntax
   - np.lexsort((key2, key1))


In [6]:
names = np.array(["John", "Alice", "Bob", "Alice"])
scores = np.array([85, 90, 85, 95])

index = np.lexsort((scores, names))
print(index)
print(names[index])
print(scores[index])

[1 3 2 0]
['Alice' 'Alice' 'Bob' 'John']
[90 95 85 85]


- Sorting Priority

   - Primary key → names
   - Secondary key → scores

# PART 2: SEARCHING FUNCTIONS

4. where()
  - where() returns the indices of elements that satisfy a given condition.

- Syntax
   - np.where(condition)

In [7]:
a = np.array([10, 25, 30, 15, 40])

result = np.where(a > 20)
print(result)

(array([1, 2, 4]),)


- Using where for Value Replacement

In [8]:
new = np.where(a > 20, "High", "Low")
print(new)

['Low' 'High' 'High' 'Low' 'High']


5. nonzero()
  - nonzero() returns the indices of all non-zero elements.



- Syntax
  - np.nonzero(array)

In [9]:
a = np.array([0, 5, 0, 3, 0, 8])

print(np.nonzero(a))

(array([1, 3, 5]),)


In [10]:
# 2D Example
b = np.array([[0, 1],
              [2, 0]])

print(np.nonzero(b))

(array([0, 1]), array([1, 0]))


6. searchsorted()
- searchsorted() finds the index where a value should be inserted to maintain sorted order.



- Important Requirement

   - Array must already be sorted.



- Syntax
   - np.searchsorted(array, value, side="left")

In [11]:
a = np.array([10, 20, 30, 40])

print(np.searchsorted(a, 25))
print(np.searchsorted(a, 30))

2
2


- Using side Parameter

In [12]:
print(np.searchsorted(a, 30, side="right"))

3


- Use Case

   - Binary search

   - Fast insertion index

   - Time-series data lookup

# COMPARISON SUMMARY TABLE
| Function       | Purpose               |
| -------------- | --------------------- |
| sort()         | Sort values           |
| argsort()      | Get sorting indices   |
| lexsort()      | Multi-key sorting     |
| where()        | Conditional search    |
| nonzero()      | Find non-zero indices |
| searchsorted() | Find insertion index  |