# Statistical Operations in NumPy

- Statistical operations are used to analyze numerical data and extract meaningful information such as average, spread, variation, and distribution.

- These operations are extremely important in:

   - Data Analysis

   - Data Science

   - Machine Learning

   - Research & Engineering

### 1. mean()
 - The mean is the average of all elements.

- NumPy Function
   - np.mean(array)

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.mean(arr))

30.0


In [2]:
# Axis Usage
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(np.mean(arr2, axis=0))  # column-wise
print(np.mean(arr2, axis=1))  # row-wise

[2.5 3.5 4.5]
[2. 5.]


### 2. median()
- The median is the middle value after sorting the data.

   - Odd count → middle value

   - Even count → average of two middle values

- NumPy Function
   - np.median(array)

In [3]:
arr = np.array([5, 1, 9, 3, 7])
print(np.median(arr))

5.0


- Sorted: [1, 3, 5, 7, 9]
- Median = 5

### 3. std() – Standard Deviation
- Standard deviation measures how much data deviates from the mean.

   - Low std → data close to mean

   - High std → data spread out

- NumPy Function
   - np.std(array)

In [4]:
arr = np.array([10, 12, 14, 16, 18])
print(np.std(arr))

2.8284271247461903


### 4. var() – Variance
- Variance is the square of standard deviation.

- Variance =(Standard Deviation)**2

- NumPy Function
   - np.var(array)

In [5]:
arr = np.array([10, 12, 14, 16, 18])
print(np.var(arr))

8.0


### 5. ptp() – Peak to Peak
- Returns the difference between maximum and minimum value.
- ptp = max − min

- NumPy Function
   - np.ptp(array)

In [6]:
arr = np.array([5, 10, 20, 40])
print(np.ptp(arr))

35


### 6. percentile()
- A percentile tells the value below which a given percentage of data lies.

- Examples:

  - 25th percentile → Q1

  - 50th percentile → Median

  - 75th percentile → Q3

- NumPy Function
  - np.percentile(array, percentile_value)

In [7]:
arr = np.array([10, 20, 30, 40, 50])
print(np.percentile(arr, 25))
print(np.percentile(arr, 50))
print(np.percentile(arr, 75))

20.0
30.0
40.0


### 7. histogram()
- A histogram shows frequency distribution of data.

- NumPy Function
   - np.histogram(array, bins)

In [8]:
arr = np.array([1, 2, 2, 3, 3, 3, 4, 5])

hist, bins = np.histogram(arr, bins=4)
print(hist)
print(bins)

[1 2 3 2]
[1. 2. 3. 4. 5.]


- Output

  - hist → frequency

  - bins → data range intervals