# Vectorized Operations
- Vectorized operations are operations that are applied simultaneously on all elements of a NumPy array without using explicit Python loops.

- Instead of processing one element at a time, NumPy processes the entire array in one operation.


# Why Vectorization Exists
- Python loops are:

   - Slow

   - Memory inefficient

   - Not suitable for large data

- NumPy vectorization:

   - Uses optimized C code internally

   - Eliminates Python-level loops

   - Executes much faster

# Comparison: Loop vs Vectorized Operation
- Using Python Loop

In [1]:
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

result = []
for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)

[6, 8, 10, 12]


- Using NumPy Vectorization 

In [2]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a + b)

[ 6  8 10 12]


- Why Vectorized is Better

  - Shorter code

  - Faster execution

  - Cleaner syntax

# 1. Element-wise Operations
- Each element in one array interacts with the corresponding element in another array.

In [3]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]


- Important Rule

   - Arrays must have:
   
      - Same shape or
      - Compatible shapes (via broadcasting)

# 2. Arithmetic Operations
- NumPy supports direct arithmetic operators.
- Operators Supported
| Operator | Meaning        |
| -------- | -------------- |
| +        | Addition       |
| -        | Subtraction    |
| *        | Multiplication |
| /        | Division       |
| //       | Floor division |
| %        | Modulus        |
| **       | Power          |


In [4]:
a = np.array([1, 2, 3])

print(a + 5)
print(a * 2)
print(a ** 2)

[6 7 8]
[2 4 6]
[1 4 9]


In [5]:
# Equivalent Functions
np.add(a, 5)
np.multiply(a, 2)
np.power(a, 2)

array([1, 4, 9])

# 3. Comparison Operations
- Comparison operations compare elements and return Boolean values (True/False).
- Operators
| Operator | Description           |
| -------- | --------------------- |
| >        | Greater than          |
| <        | Less than             |
| >=       | Greater than or equal |
| <=       | Less than or equal    |
| ==       | Equal                 |
| !=       | Not equal             |

In [6]:
a = np.array([10, 20, 30, 40])

print(a > 25)

[False False  True  True]


- Use Case

   - Filtering data

   - Conditional selection

   - Data cleaning

# 4. Logical Operations
- Logical operations are used to combine multiple conditions
- Logical Operators

In [7]:
a = np.array([10, 20, 30, 40, 50])

print((a > 20) & (a < 50))

[False False  True  True False]


- Using NumPy Functions

In [8]:
np.logical_and(a > 20, a < 50)
np.logical_or(a < 20, a > 40)
np.logical_not(a > 30)

array([ True,  True,  True, False, False])

# 5. Broadcasting
- Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array.

In [9]:
a = np.array([1,2,3])
print(a + 10)

[11 12 13]


- How Broadcasting Works

   - Scalar 10 is stretched to [10,10,10]

   - Operation performed element-wise

- Broadcasting Rules (NO SHORTCUT)
   - Rule 1: Compare Shapes from Right
       - Compare array dimensions from right to left.



   - Rule 2: Dimensions are Compatible If
       - They are equal, OR
       - One of them is 1



   - Rule 3: Incompatible Shapes → Error
       - ValueError: operands could not be broadcast together

In [10]:
# 1D + 2D Example
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([10,20,30])

print(a + b)

[[11 22 33]
 [14 25 36]]


In [11]:
# Column Broadcasting
c = np.array([[1],
              [2]])

print(a + c)

[[2 3 4]
 [6 7 8]]


- Why Broadcasting is Powerful

   - Eliminates loops

   - Saves memory

   - Speeds up computation

   - Essential in ML algorithms